export const mockBreeds = [
  { value: 'labrador', label: 'Labrador Retriever' },
  { value: 'german-shepherd', label: 'German Shepherd' },
  { value: 'golden-retriever', label: 'Golden Retriever' },
  { value: 'bulldog', label: 'Bulldog' },
  { value: 'beagle', label: 'Beagle' },
  { value: 'poodle', label: 'Poodle' },
  { value: 'rottweiler', label: 'Rottweiler' },
  { value: 'yorkshire-terrier', label: 'Yorkshire Terrier' },
  { value: 'boxer', label: 'Boxer' },
  { value: 'dachshund', label: 'Dachshund' },
  { value: 'siberian-husky', label: 'Siberian Husky' },
  { value: 'great-dane', label: 'Great Dane' },
  { value: 'doberman-pinscher', label: 'Doberman Pinscher' },
  { value: 'australian-shepherd', label: 'Australian Shepherd' },
  {
    value: 'cavalier-king-charles-spaniel',
    label: 'Cavalier King Charles Spaniel',
  },
  { value: 'shih-tzu', label: 'Shih Tzu' },
  { value: 'boston-terrier', label: 'Boston Terrier' },
  { value: 'pomeranian', label: 'Pomeranian' },
  { value: 'havanese', label: 'Havanese' },
  { value: 'bernese-mountain-dog', label: 'Bernese Mountain Dog' },
  { value: 'corgi', label: 'Corgi' },
  { value: 'border-collie', label: 'Border Collie' },
  { value: 'mastiff', label: 'Mastiff' },
  { value: 'bichon-frise', label: 'Bichon Frise' },
  { value: 'newfoundland', label: 'Newfoundland' },
  { value: 'bloodhound', label: 'Bloodhound' },
  { value: 'spoodle', label: 'Spoodle' },
  { value: 'labradoodle', label: 'Labradoodle' },
  { value: 'goldendoodle', label: 'Goldendoodle' },
  { value: 'other', label: 'Other' },
]
